angular.module('cabalaApp').factory('MagicAndMeaningOfNumbersBean', [function () {
    'use strict';

    var magicAndMeaningOfNumbers = {
        '1': 'O princípio ativo, celeste, o centro, a essência, o criador, o ponto irradiante, o masculino, a luz, o Yang, o homem de pé, o Sol, o primeiro movimento. Símbolo do Ser e da Revelação. Simboliza a unidade, a onipotência divina, o princípio de todas as coisas, a individualidade, a espontaneidade, a força de vontade, a energia e a criatividade. É o início de tudo, são as novas oportunidades, a busca do inusitado. Ele traz coragem, dinamismo, independência, é um número forte. O seu lado negativo pode gerar um excesso de confiança e acabar transformando a liderança num domínio muito autoritário.',
        '2': 'O primeiro passivo, terrestre. o Yin, o reflexo, a duplicação, a alternância, o feminino, a primeira divisão em direção a multiplicidade. Representa a Lua, a complementação, a substância que recebe a essência. Simboliza a duplicidade, a dúvida, a discórdia, o antagonismo, mas também o equilíbrio, o movimento que constrói o progresso. É a manifestação das oposições, do criador e da criatura, da vida e da morte, do céu e da terra, do ativo e do passivo, do homem e da mulher, do bem e do mal. É o número do equilíbrio, do senso de justiça e do crescimento espiritual. Ele confere gentileza, compreensão e sabedoria. Sua influência traz grande capacidade de adaptação e a busca de harmonia nos relacionamentos. O seu lado negativo é a passividade, que pode acabar por aceitar todas as imposições alheias.',
        '3': 'A síntese, a solução do conflito dual, o número da expressão da totalidade, da perfeição da união do 1 com o 2, nada pode ser acrescentado a ele. O triângulo, algo muito firme em sua base. Os Três Mistérios. O triângulo mágico. Representa o homem, enquanto filho do Céu e da Terra. É ligado a comunicação e a espiritualidade. Em quase todas as religiões, existe uma trindade divina, representada por uma divindade masculina, uma feminina e um “filho”, fruto dessa união. O ternário é o dogma universal. Sugere também a intuição, a ação, o progresso, a liderança. Número da comunicação e da alegria de viver. Normalmente traz facilidade no contato com os outros e indica grande talento, principalmente nas artes da oratória e da literatura. É carregado de otimismo e despreocupação. O lado negativo mostra que ele pode acabar dispersando todo esse talento de forma superficial, sem construir nada de significativo.',
        '4': 'O sólido, o tangível, o terrestre o que foi revelado. Relaciona-se ao quadrado e à cruz. Caracteriza o universo em sua totalidade, com os quatro pontos cardinais, os quatro elementos, etc. Quatro Virtudes. O quadrado mágico. É um número de limitação, acomodação, de ligação com a realidade. Está associado à Terra. Gera estabilidade e segurança material. Sugere também o poder, a força de vontade e a certeza “material”. É o número do equilíbrio, da decisão e da seriedade. Tem grande senso de responsabilidade, apego à rotina e às tradições. Está ligado ao trabalho, à dedicação e à capacidade de construção. O seu lado negativo aparece quando ele põe toda a sua potencialidade no sentido de destruição. Nota: o nome Deus é escrito com 4 letras em diversos idiomas...',
        '5': 'A união, centro da harmonia e do equilíbrio, o homem. Simboliza a vontade divina, os cinco sentidos, as cinco formas sensíveis da matéria. O pentagrama, a flor de cinco pétalas no centro da cruz hermética. É o número do casamento, do centro, a soma do primeiro número par 2, com o primeiro número ímpar 3, uma vez que o número 1 não é considerado. No hinduísmo, o cinco é o princípio de todas as coisas. Simboliza síntese e união. Sugere um desprendimento da matéria para se voltar mais à espiritualidade. E está associado à bondade, à generosidade e o perdão. Também é o número da rebeldia, da aventura e da curiosidade. Está muito ligado aos prazeres, especialmente aos relacionados aos sentidos. Ele confere geralmente rapidez de raciocínio, amor à liberdade, às mudanças e boa capacidade de adaptação. O lado negativo se dá quando ele não assume as responsabilidades ou quando usa seus atributos para enganar ou ludibriar os outros.',
        '6': 'Os dons recíprocos, o bem e o mal, o antagonismo, o macrocosmo. Simboliza a perfeita criação, tal como é vista no selo de Salomão (a estrela de seis pontas). Relaciona-se a besta do Apocalipse, pois na Bíblia é o número do pecado. É o número do amor, da emotividade, dos laços, da doação, da ternura, da escolha, das dúvidas. É o número do amor ao belo, do idealismo e do romantismo. Traz simpatia e afetuosidade, mas também um grande apego às tradições e à família. Quer sempre ter beleza e harmonia ao seu redor. Seu lado negativo aparece quando quer impor seus próprios ideais a todos os outros.',
        '7': 'A totalidade do universo em movimento, os 7 dias da semana, os 7 planetas visíveis, as 7 cores do arco-íris, as 7 notas da escala musical diatônica, os 7 Sacramentos, os 7 gênios, os 7 anjos que conforme o Apocalipse, estão sempre diante do trono de Deus. Simboliza o dinamismo resultante, a aliança de Deus com a humanidade. Representa a plenitude, a individualidade, a riqueza, a perfeição, o período completo ou o ciclo completo. Está associado à Lua (cada fase lunar dura sete dias) e é tido como um número sagrado. Representa as más influências da vida agindo sobre o indivíduo e a certeza de ultrapassar estas barreiras e de vencer o ciclo natural do bem e do mal, assim completando e findando o ciclo promete a certeza da realização. É o número da espiritualidade, do misticismo e da introspecção. Tem muita sensibilidade, fantasia e criatividade, mas sempre voltadas para si próprio. Conduz à busca da tranquilidade e da paz interior. O lado negativo é a instabilidade emocional e a tendência a dar muita importância à fantasia, afastando-se da realidade externa.',
        '8': 'O equilíbrio cósmico, o número dos raios da roda, a ressurreição, a transfiguração, que sucede aos 7 dias da Criação. Símbolo da eternidade, matematicamente representado pelo número 8 na horizontal (lemniscata) é a clássica representação do infinito, a comunhão perfeita entre o consciente e o inconsciente e do conhecimento esotérico. Representa a harmonia da obra terminada. É o número da ordem e do equilíbrio cósmicos. Está associado às ideias de justiça e harmonia. Sugere a imparcialidade e a capacidade de julgar seus atos como dos outros. Representa também a força moral e a integridade, o equilíbrio entre o bem e o mal. Número do equilíbrio material e espiritual, da capacidade de administração e do trabalho duro. Traz uma grande possibilidade de realização financeira. É organizado e realista. Seu lado negativo pode surgir quando ele se volta somente para o aspecto material, abandonando o espiritual.',
        '9': 'A gestação, a busca proveitosa, o término de uma obra, a recompensa final. É o número da plenitude, das esferas celestes, dos coros angélicos (no Cristianismo é o número dos coros dos anjos celestiais), das musas. Quadrado de 3, representa a universalidade :  símbolo da Fé Bahai. Sendo o último número de um algarismo, ou o último do ciclo, ele traz uma visão mais ampla do mundo e das pessoas, relaciona-se ao fecho do círculo. É considerado no esoterismo, o número da perfeição e está associado a perfeição moral e ao consciente, trazendo assim o conhecimento, a sabedoria, a paciência, o senso, a dedicação e a prudência. É o número do humanismo, da generosidade, tem uma forte intuição e imaginação. Geralmente gosta de grandes viagens. O lado negativo vem quando a capacidade de compreensão da vida é mal aplicada, servindo para fins prejudiciais.',
        '10': 'Representa o ponto final das unidades e portanto, o retorno ao ponto de partida, ao número 1. Esta associado aos elementos naturais da vida, o bem e o mal, a vida e a morte, as alegrias e as tristezas, assim o mundo vira, assim a vida gira tendo seus altos e baixos, e assim o ciclo continua terminando uma fase e começando outra. Sugere mudanças e faz parte do destino. É a soma dos quatro primeiros números, onde está a fonte da natureza, da qual tudo flui e para a qual tudo retorna. Representa a totalidade, um todo fechado em si mesmo, a volta à unidade, os 10 Mandamentos, as esferas da Árvore da Vida.',
        '11': 'Número dos mistérios da fecundidade, da renovação dos ciclos vitais. Soma de 5 e 6, representa a ligação do Céu e da Terra (o Tao). Relaciona-se as palavras “abracadabra” e “alendalenda”, usadas como proteção, capazes de colocar aquele que busca em harmonia, com as forças cósmicas e telúricas. O onze é considerado de maneira à parte e é chamado de número mestre. Sua energia é muito forte, ele permite uma mente intuitiva, criativa, progressista e idealista, que normalmente consegue ver além das aparências. O seu lado negativo aparece quando ele não consegue administrar todo esse potencial benéfico e acaba se perdendo na busca de um “paraíso fácil”.',
        '12': 'Número das divisões espaço temporais. Casamento do 3 (os planos do mundo) e do 4 (os pontos cardeais). O Universo e sua multiplicidade interna. Algo fundamental. O Zodíaco (os doze signos), os 12 Apóstolos, as 12 tribos de Israel, os 12 meses do ano, os 12 Cavaleiros da Távola Redonda. É o número da eleição, do círculo concluído. Representado pelo Enforcado, no Tarôt.',
        '13': 'Na Antiguidade o número 13 tornou-se de mau agouro, depois que o Imperador Felipe da Macedônia acrescentou sua estátua às do doze deuses do Olimpo. Logo em seguida, ele foi brutalmente assassinado. É ambivalente, o décimo terceiro capítulo do Apocalipse refere-se ao anticristo e à besta. Em contra partida, Zeus é o décimo terceiro no cortejo olímpico. Relaciona-se à noção de poder e glória. Anuncia o recomeço. Existem treze cartas de cada naipe no Baralho. Jesus e os 12 Apóstolos. Jacó e as 12 Tribos de Israel. O Rei Arthur e os 12 cavaleiros. Robin Hood e seus 12 alegres companheiros. Simbolizado pela Morte, no Tarôt.',
        '14': 'Representa a perfeição também (= 2 × 7).',
        '16': 'Quadrado de 4, o quadrado do quadrado, representa a completa realização no plano concreto e material. Pode simbolizar o extremo orgulho, o poder sem controle, o abismo. O dobro de 8, relaciona-se aos ciclos de encarnação. É a Torre, no Tarôt.',
        '17': 'Número venerado no Islã, soma de 8 e 9, relaciona-se ao 72 (produto de 8 e 9). São 17 os gestos litúrgicos na tradição muçulmana, 17 palavras compõem o chamado à prece. Associa-se às ideias de liberação cármica, mutação e renascimento.',
        '20': 'O Homem Perfeito, para os maias representa a Deus Solar, número cultuado por várias tradições indígenas por estar associado aos 20 dedos humanos. Simbolizado pelo Julgamento, no Tarôt.',
        '21': 'Os atributos da sabedoria, a perfeição por excelência, a livre escolha, entre bem e mal, a responsabilidade. Curiosamente escolhido como marco da maioridade para muitos povos. Evoca a realização, a meta alcançada, a plenitude. No Tarôt é o Mundo.',
        '22': 'A manifestação do ser no espaço e no tempo, as 22 letras hebraicas que representam o Universo da Cabala, símbolo das formas naturais e da história da Criação. Os 22 Arcanos Maiores do Tarôt, os 22 capítulos do Apocalipse de São João. É o número do Universo. Este também é um número mestre, que além de conferir uma excelente compreensão do universo, permite a concretização dos ideais. Ele traz ainda uma grande dose de intelectualidade, o que equilibra a sua parte idealista. O lado negativo deste número só aflora quando ele abandona suas próprias convicções e se deixa levar pelas ideias alheias.',
        '24': 'Representa a duplicação da harmonia entre Céu e Terra. Simboliza também a roda dos renascimentos, com seus 24 raios. É o número dos anciãos do Apocalipse, na Bíblia, relaciona-se com a medida da história humana.',
        '36': 'Relaciona-se ao encontro dos elementos em suas evoluções cíclicas, simbolizando a solidariedade cósmica. É o grande quaternário dos pitagóricos, pois é a soma dos quatro primeiros números pares com os quatro primeiros números ímpares (20 + 16). Existem 36 talismãs de Salomão.',
        '40': 'É o número da provação, do castigo, da espera e da preparação. Moisés passa 40 dias no Monte Sinai, Jesus prega por 40 meses e ressuscita depois de 40 horas no sepulcro, Noé enfrenta 40 dias e 40 noites de dilúvio. Medida de quarentena, do resguardo e da quaresma. Existem 40 cartas numeradas dentro do Baralho Cigano, durante 40 anos os israelitas vagaram pelo deserto à procura da Terra Prometida.',
        '49': 'Quadrado de sete, representa, em diferentes tradições, o período de espera para a alma de uma pessoa falecida ganhar definitivamente um novo lar. Simboliza o final de uma longa jornada, ou o término de um tempo de espera.',
        '64': 'Quadrado de 8, representa a realização terrestre, a perfeição de algo completo, a plenitude. Associa-se também ao campo delimitado de batalha, representado pelo tabuleiro de xadrez. Jesus Cristo seria a sexagésima quarta geração depois de Adão, segundo São Lucas.',
        '70': 'Como todos os múltiplos de 7, relaciona-se à totalidade, à universalidade, à expressão do ilimitado. Representa os habitantes do mundo, os 70 povos da Terra, dispersos após a construção da Torre de Babel.',
        '72': 'Produto de 9 e 8, números relacionados à harmonia das esferas, representa equilíbrio e proporção. Símbolo da Criação (7) manifestada, em perfeito equilíbrio (2). A soma de seus algarismos é 9 e são 9 os números dos quais é múltiplo: 2, 3, 6, 8, 9, 12, 18, 24, 36.',
        '99': 'Na tradição esotérica islâmica (o sufixo) é o número dos nomes conhecidos de Deus. Múltiplo de 33, idade mística de Jesus Cristo, carrega em si a revelação, a expressão do Divino na humanidade.',
        '100': 'Parte do todo, conjunto que se destaca num todo maior. Microcosmo inserido no macrocosmo. Porção individualizada, que possui função específica dentro do contexto mais amplo. Atribui uma qualidade específica ao que é enumerado.',
        '108': 'Como o 36 (número do céu) e o 72 (número da terra), o 108 (número do homem) é muito apreciado por várias sociedades secretas. Representa a harmonia. Podemos encontrá-lo no triângulo isósceles (com 108 graus), que dá as proporções do número de ouro.',
        '365': 'O processo cíclico completo, representa o ciclo cósmico. Se acrescentarmos uma unidade representará a saída do círculo, a abertura que possibilita escapar do ciclo, da permanência para a eternidade.',
        '666': 'O número do Anticristo, o máximo da fraqueza.',
        '777': 'O número do Messias, o máximo da perfeição.',
        '1000': 'Significa multidão.',
        '10000': 'Simboliza a abundância, a fecundidade. Na China, representa a totalidade de tudo que há sobre a Terra. Relaciona-se à quantidade que não pode ser contada. Refere-se também ao reino de Cristo, onde cada semente produzirá dez mil grãos.'
    };

    return magicAndMeaningOfNumbers;
}]);